### ISSUE TITLE
Follow does not work 

### ISSUE THREAD

**Issue by WuerfelDev** [altdesktop/playerctl#249] opened 2021-09-14 14:46 UTC
The player I am using is Brave Browser.

I noticed that my script doesn't show the next playing song, so I saw that running `playerctl metadata -F` prints the correct output, but once the next song starts I get these "warnings" instead:

```
❯playerctl metadata -F
chromium xesam:album
chromium xesam:artist              KatyPerryVEVO
chromium xesam:title               Katy Perry - Firework (Official Music Video)

(playerctl:366162): playerctl-WARNING **: 16:01:52.028: mpris:trackid is a string, not a D-Bus object reference

(playerctl:366162): playerctl-WARNING **: 16:01:52.028: mpris:trackid is a string, not a D-Bus object reference

(playerctl:366162): playerctl-WARNING **: 16:01:52.984: mpris:trackid is a string, not a D-Bus object reference

(playerctl:366162): playerctl-WARNING **: 16:01:52.995: mpris:trackid is a string, not a D-Bus object reference
```

Every now song generates this 'warning" 4 times. The next info stays hidden.

Running playerctl v2.3.1 from ubuntu repos

**Comment by acrisci** [comment] 2021-09-20 21:09
I believe this is fixed on master branch. I can't reproduce it.

**Closed** 2021-11-08 03:18 UTC
Labels: bug
