### ISSUE TITLE
Playerctl not working with chromium

### ISSUE THREAD

**Issue by jfamousket** [altdesktop/playerctl#206] opened 2020-11-23 09:03 UTC
Hey, firstly nice proect! :heart: 
There seems to be a bug with chromium, it errors out as shown below
Tested with `youtube.com` `music.youtube.com` and `soundcloud.com`

![image](https://user-images.githubusercontent.com/40635633/99944130-abfdf100-2d72-11eb-8550-9df2b11c42be.png)

Here's my chromium build
![image](https://user-images.githubusercontent.com/40635633/99944336-faab8b00-2d72-11eb-94ac-f293fc8a59a5.png)

**Comment by acrisci** [comment] 2020-11-24 18:29
I'm using the same version of Chromium and cannot reproduce this. It works fine for me.

**Comment by benjaminBrownlee** [comment] 2020-11-25 15:41
I think its common for browsers to have flags to toggle MPRIS interface exposure. Did you check those? Also, do you see the MPRIS information registered on dbus on any other tools (python has a very easy tool to use)? If it isn't registered there when it should be then the issue is with Chromium and probably out of scope of this project.

**Comment by jfamousket** [comment] 2020-11-26 08:58
For sure chrome exposes an MPRIS interface as you can see 
![image](https://user-images.githubusercontent.com/40635633/100312988-ef936d80-2fb3-11eb-8a61-ca9aa2789c6c.png)

Here's the output from `dbus-monitor` after a running `playerctl play-pause` with an instance of chromium running and a video playing in youtube.
```
method call time=1606381133.757612 sender=:1.21 -> destination=org.freedesktop.DBus serial=1 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=Hello
method return time=1606381133.757661 sender=org.freedesktop.DBus -> destination=:1.21 serial=1 reply_serial=1
   string ":1.21"
signal time=1606381133.757701 sender=org.freedesktop.DBus -> destination=(null destination) serial=19 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameOwnerChanged
   string ":1.21"
   string ""
   string ":1.21"
signal time=1606381133.757761 sender=org.freedesktop.DBus -> destination=:1.21 serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
   string ":1.21"
method call time=1606381133.758955 sender=:1.21 -> destination=org.freedesktop.DBus serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=AddMatch
   string "type='signal',sender='org.freedesktop.DBus',interface='org.freedesktop.DBus.Properties',member='PropertiesChanged',path='/org/freedesktop/DBus',arg0='org.freedesktop.DBus'"
method return time=1606381133.759022 sender=org.freedesktop.DBus -> destination=:1.21 serial=3 reply_serial=2
method call time=1606381133.759112 sender=:1.21 -> destination=org.freedesktop.DBus serial=3 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=AddMatch
   string "type='signal',sender='org.freedesktop.DBus',interface='org.freedesktop.DBus',path='/org/freedesktop/DBus'"
method return time=1606381133.759162 sender=org.freedesktop.DBus -> destination=:1.21 serial=4 reply_serial=3
method call time=1606381133.759258 sender=:1.21 -> destination=org.freedesktop.DBus serial=4 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=AddMatch
   string "type='signal',sender='org.freedesktop.DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',path='/org/freedesktop/DBus',arg0='org.freedesktop.DBus'"
method return time=1606381133.759307 sender=org.freedesktop.DBus -> destination=:1.21 serial=5 reply_serial=4
method call time=1606381133.759685 sender=:1.21 -> destination=org.freedesktop.DBus serial=5 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=StartServiceByName
   string "org.freedesktop.DBus"
   uint32 0
error time=1606381133.759731 sender=org.freedesktop.DBus -> destination=:1.21 error_name=org.freedesktop.DBus.Error.ServiceUnknown reply_serial=5
   string "The name org.freedesktop.DBus was not provided by any .service files"
method call time=1606381133.760595 sender=:1.21 -> destination=org.freedesktop.DBus serial=6 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=GetNameOwner
   string "org.freedesktop.DBus"
method return time=1606381133.760644 sender=org.freedesktop.DBus -> destination=:1.21 serial=7 reply_serial=6
   string "org.freedesktop.DBus"
method call time=1606381133.761467 sender=:1.21 -> destination=org.freedesktop.DBus serial=7 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus.Properties; member=GetAll
   string "org.freedesktop.DBus"
method return time=1606381133.761515 sender=org.freedesktop.DBus -> destination=:1.21 serial=8 reply_serial=7
   array [
      dict entry(
         string "Features"
         variant             array [
               string "SystemdActivation"
            ]
      )
      dict entry(
         string "Interfaces"
         variant             array [
               string "org.freedesktop.DBus.Monitoring"
               string "org.freedesktop.DBus.Debug.Stats"
            ]
      )
   ]
method call time=1606381133.770227 sender=:1.21 -> destination=org.freedesktop.DBus serial=8 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=StartServiceByName
   string "org.freedesktop.DBus"
   uint32 0
error time=1606381133.770284 sender=org.freedesktop.DBus -> destination=:1.21 error_name=org.freedesktop.DBus.Error.ServiceUnknown reply_serial=8
   string "The name org.freedesktop.DBus was not provided by any .service files"
method call time=1606381133.771200 sender=:1.21 -> destination=org.freedesktop.DBus serial=9 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=GetNameOwner
   string "org.freedesktop.DBus"
method return time=1606381133.771249 sender=org.freedesktop.DBus -> destination=:1.21 serial=10 reply_serial=9
   string "org.freedesktop.DBus"
method call time=1606381133.772128 sender=:1.21 -> destination=org.freedesktop.DBus serial=10 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus.Properties; member=GetAll
   string "org.freedesktop.DBus"
method return time=1606381133.772176 sender=org.freedesktop.DBus -> destination=:1.21 serial=11 reply_serial=10
   array [
      dict entry(
         string "Features"
         variant             array [
               string "SystemdActivation"
            ]
      )
      dict entry(
         string "Interfaces"
         variant             array [
               string "org.freedesktop.DBus.Monitoring"
               string "org.freedesktop.DBus.Debug.Stats"
            ]
      )
   ]
method call time=1606381133.773174 sender=:1.21 -> destination=org.freedesktop.DBus serial=11 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=ListNames
method return time=1606381133.773214 sender=org.freedesktop.DBus -> destination=:1.21 serial=12 reply_serial=11
   array [
      string "org.freedesktop.DBus"
      string "org.freedesktop.Notifications"
      string "org.freedesktop.ReserveDevice1.Audio0"
      string "org.freedesktop.systemd1"
      string ":1.20"
      string ":1.21"
      string ":1.10"
      string "org.mpris.MediaPlayer2.chromium.instance6013"
      string ":1.11"
      string ":1.12"
      string "org.awesomewm.awful"
      string ":1.0"
      string "org.pulseaudio.Server"
      string "org.PulseAudio1"
      string ":1.2"
      string ":1.3"
      string ":1.4"
      string "ca.desrt.dconf"
      string ":1.5"
      string ":1.19"
   ]
method call time=1606381133.779116 sender=:1.21 -> destination=org.freedesktop.DBus serial=12 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=AddMatch
   string "type='signal',sender='org.mpris.MediaPlayer2.chromium.instance6013',interface='org.freedesktop.DBus.Properties',member='PropertiesChanged',path='/org/mpris/MediaPlayer2',arg0='org.mpris.MediaPlayer2.Player'"
method return time=1606381133.779202 sender=org.freedesktop.DBus -> destination=:1.21 serial=13 reply_serial=12
method call time=1606381133.779356 sender=:1.21 -> destination=org.freedesktop.DBus serial=13 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=AddMatch
   string "type='signal',sender='org.mpris.MediaPlayer2.chromium.instance6013',interface='org.mpris.MediaPlayer2.Player',path='/org/mpris/MediaPlayer2'"
method return time=1606381133.779406 sender=org.freedesktop.DBus -> destination=:1.21 serial=14 reply_serial=13
method call time=1606381133.779423 sender=:1.21 -> destination=org.freedesktop.DBus serial=14 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=AddMatch
   string "type='signal',sender='org.freedesktop.DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',path='/org/freedesktop/DBus',arg0='org.mpris.MediaPlayer2.chromium.instance6013'"
method return time=1606381133.779459 sender=org.freedesktop.DBus -> destination=:1.21 serial=15 reply_serial=14
method call time=1606381133.779823 sender=:1.21 -> destination=org.freedesktop.DBus serial=15 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=StartServiceByName
   string "org.mpris.MediaPlayer2.chromium.instance6013"
   uint32 0
error time=1606381133.779868 sender=org.freedesktop.DBus -> destination=:1.21 error_name=org.freedesktop.DBus.Error.ServiceUnknown reply_serial=15
   string "The name org.mpris.MediaPlayer2.chromium.instance6013 was not provided by any .service files"
method call time=1606381133.780822 sender=:1.21 -> destination=org.freedesktop.DBus serial=16 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=GetNameOwner
   string "org.mpris.MediaPlayer2.chromium.instance6013"
method return time=1606381133.780912 sender=org.freedesktop.DBus -> destination=:1.21 serial=17 reply_serial=16
   string ":1.4"
method call time=1606381133.781585 sender=:1.21 -> destination=:1.4 serial=17 path=/org/mpris/MediaPlayer2; interface=org.freedesktop.DBus.Properties; member=GetAll
   string "org.mpris.MediaPlayer2.Player"
method return time=1606381133.782662 sender=:1.4 -> destination=:1.21 serial=14 reply_serial=17
   array [
      dict entry(
         string "CanControl"
         variant             boolean true
      )
      dict entry(
         string "CanGoNext"
         variant             boolean false
      )
      dict entry(
         string "CanGoPrevious"
         variant             boolean false
      )
      dict entry(
         string "CanPause"
         variant             boolean false
      )
      dict entry(
         string "CanPlay"
         variant             boolean false
      )
      dict entry(
         string "CanSeek"
         variant             boolean false
      )
      dict entry(
         string "MaximumRate"
         variant             double 1
      )
      dict entry(
         string "Metadata"
         variant             array [
               dict entry(
                  string "xesam:album"
                  variant                      string ""
               )
               dict entry(
                  string "xesam:artist"
                  variant                      array [
                        string "MrMobile [Michael Fisher]"
                     ]
               )
               dict entry(
                  string "xesam:title"
                  variant                      string "When Phones Were Fun: Sony Ericsson Xperia Pureness (2009)"
               )
            ]
      )
      dict entry(
         string "MinimumRate"
         variant             double 1
      )
      dict entry(
         string "PlaybackStatus"
         variant             string "Playing"
      )
      dict entry(
         string "Position"
         variant             int64 0
      )
      dict entry(
         string "Rate"
         variant             double 1
      )
      dict entry(
         string "Volume"
         variant             double 1
      )
   ]
signal time=1606381133.784680 sender=org.freedesktop.DBus -> destination=:1.21 serial=20 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameLost
   string ":1.21"
signal time=1606381133.784738 sender=org.freedesktop.DBus -> destination=(null destination) serial=21 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameOwnerChanged
   string ":1.21"
   string ":1.21"
   string ""

```

**Comment by acrisci** [comment] 2020-11-26 17:08
In that state, the player cannot be sent some commands because for instance the `CanPause` property is set to false.

```
      dict entry(
         string "CanPause"
         variant             boolean false
      )
```

This is either a bug or misconfiguration in Chromium.

**Comment by jfamousket** [comment] 2020-11-27 08:34
Ahh, thanks I found the issue, I made another chrome plugin before to control my playback with media hotkeys, seems like this was hugging the control. Removed it and it works perfectly now, cheers :clinking_glasses:

**Closed** 2020-11-27 08:34 UTC
Labels: bug
