### ISSUE TITLE
Re-print playing player(s) in --follow

### ISSUE THREAD

**Issue by FichteFoll** [altdesktop/playerctl#221] opened 2021-01-17 11:35 UTC
I am using `playerctl --follow` for a polybar module with the following command:
```
playerctl --follow metadata -f '{{status}}%{F#555}{{playerName}}%{F-} {{artist}} - {{title}}' | sed -u 's/^Paused.*/-/; s/^Stopped.*/-/; s/^Playing//'
```

I want it to display the currently playing media, while showing just `-` when nothing is playing.

However, because playerctl only prints something if a player's information changed, pausing a player while 2 are running does not cause the playing one to have its line re-printed. Is this something playerctl would be interested in or do I have to write a wrapper?

(Also it appears that `mpd-mpris` is very spammy and causes playerctl to print stuff for `playerctl metadata -f` all the time, which is why I had to replace it with mpDris2 since it pretty much always took priority.)

**Comment by FichteFoll** [comment] 2021-01-17 11:58
I also sometimes get a sparse empty line for seemingly no reason (before the sed call).

**Comment by acrisci** [comment] 2021-01-17 20:56
> I also sometimes get a sparse empty line for seemingly no reason

You should handle this because empty line means there are no active players.

Try the `--all-players` flag with your command because the behavior is slightly different and might be what you need.

If you want a more advanced filter, it would be easy to script. I would have to think about how to do that cleanly but I would be open to some suggestions as to how to do it.

**Comment by FichteFoll** [comment] 2021-01-18 11:44
> You should handle this because empty line means there are no active players.

Sure, the problem was that I actually had something playing. Not sure what's at fault exactly, though, since `mpDris2` also seems to close unreliably.

> Try the --all-players flag with your command because the behavior is slightly different and might be what you need.

I'll try that. Hopefully it helps.

**Comment by FichteFoll** [comment] 2021-01-18 14:55
I found one reliable reproduction case not for the blank line but for suboptimal behavior in my case.

I have mpd and mpv running, where mpd is in paused state and mpv in playing. When I seek in mpd without changing the playback state, playerctl prints mpd until there is a change in mpv, e.g. I pause and play or the next file starts playing.

```
~ ▶ playerctl --follow metadata -f '{{status}}%{F#555}{{playerName}}%{F-} {{artist}} - {{title}}' --all-players 2>/dev/null
Playing%{F#555}mpv%{F-}  - 平手友梨奈 『ダンスの理由』MUSIC VIDEO
Paused%{F#555}mpd%{F-} Lucid Planet - Anamnesis
```

**Comment by acrisci** [comment] 2021-01-18 16:08
This is by design. Any user interaction will "activate" a player and send it to the top of the list.

**Comment by FichteFoll** [comment] 2021-01-18 16:50
I agree that this behavior makes sense, especially if you don't use the `-f` option. 

However, I'm wondering whether you would be interested in adding filters for this command that would for example only print playing players (or nothing/an empty line when all players are filtered).

**Comment by acrisci** [comment] 2021-01-18 16:56
Yeah I've had this request a few times. The first thing that comes to mind would be adding a `--status={status[,status]}` flag you could use to filter or prioritize. For instance

```
--status=playing # only select playing players
--status=playing,paused # prioritize playing but don't select stopped players
```

I'm open to an alternative suggestion. I wonder if it would make sense to have a generalized filter system where you could do this filtering based on any property with a DSL. That might be overkill because it would end up being more complicated than bash in the end.

What do you think?

**Comment by FichteFoll** [comment] 2021-01-18 17:04
> I wonder if it would make sense to have a generalized filter system where you could do this filtering based on any property with a DSL. That might be overkill because it would end up being more complicated than bash in the end.

Same thoughts over here. For my particular case, just the status would be enough. For a general filter, you'd need a) a way to express the source field operand, and b) a way to express a condition that should be matched. If this used a scripting language, I'd say just evaluating that with variables filled would work, but since it's C, that would not work out. Instead, a custom language would need to be formulated for various useful logic, such as 

- numeric comparisons (or ranges)
- exact matches/equality
- submatches (with regular expressions)
- and/or combinations of the above

Definitely not something I'd see the need for just to include the feature I am requesting.

What sort of other filters have been requested so far? Maybe we can thin down a list of must-have filters and start from there.

**Comment by acrisci** [comment] 2021-01-18 18:02
Yeah the formatter language could easily be adapted to be a full blown scripting language, but I don't think there is a use case for selection and prioritization beyond player name and status. Filters on anything else seems kind of worthless to me and I've never had a request for those features. If you're doing something complicated, you probably have access to bash anyway.

Let's just go with status prioritization with `--status=...` since that seems like it does what you need to do and reevaluate the general filter case later.

If you want to work on it, I can get you started on an approach. Otherwise it takes me awhile to do things like this, but I usually do these kinds of features eventually.

**Comment by FichteFoll** [comment] 2021-01-18 18:31
SGTM. Unfortunately, I have a handful things to attend to myself, so I'll have to thankfully decline your offer on getting me started on it. I'm fine with waiting a bit. Thanks for your quick answers so far.

I just want to re-empahsise (for you or anyone else) that an empty line should be printed in follow mode if all players are filtered on an update, but I suspect you would have done that anyway.

**Comment by acrisci** [comment] 2021-01-18 19:59
Closing in favor of the feature issue.

**Closed by acrisci** 2021-01-18 19:59 UTC
Labels: bug
